#!/bin/bash

set -e
QUOTEDCMD=()
for token in "$@"; do
  QUOTEDCMD+=($(printf "%q" "$token"))
done
CMD="${QUOTEDCMD[*]}"
if [[ -z "$CMD" ]]
then
  CMD="bash"
fi

PWD=$(pwd -P)

if [ -f .git ]; then
	SOURCE="${PWD}/.."
	DEST="/usr/src/app"
	CURRDIR=$(basename ${PWD})
	WORKDIR="${DEST}/${CURRDIR}"
else
	SOURCE="${PWD}"
	DEST="/usr/src/app"
	WORKDIR="/usr/src/app"
fi

docker run -v /home/$(whoami)/.memento:/home/memento/.memento -v ${SOURCE}:${DEST} -w ${WORKDIR} -it memento /bin/bash -c "memento ${CMD}"

